### ISSUE TITLE
Possible crashs because of achievements.

### ISSUE THREAD

**Issue by Nemirtingas** [acidicoala/ScreamAPI#2]
Error code is not checked for your achievement manager and could cause potential crashs.
https://github.com/acidicoala/ScreamAPI/blob/master/ScreamAPI/src/achievement_manager.cpp#L151
https://github.com/acidicoala/ScreamAPI/blob/master/ScreamAPI/src/achievement_manager.cpp#L204

Should be checked against `EOS_EResult::EOS_Success`

**Comment by acidicoala** [comment]
Hey, thanks for pointing it out. Will add error checking in the next version.

**Comment by acidicoala** [comment]
Fixed in 817250e
