### ISSUE TITLE
Overlay error when resizing window or changing in game resolution.

### ISSUE THREAD

**Issue by Nemirtingas** [acidicoala/ScreamAPI#6]
You can take a look at my overlay about detecting resizing:
https://gitlab.com/Nemirtingas/nemirtingas_steam_emu/-/blob/master/overlay/windows/DX11_Hook.cpp#L66-84
https://gitlab.com/Nemirtingas/nemirtingas_steam_emu/-/blob/master/overlay/windows/DX11_Hook.cpp#L92-141
https://gitlab.com/Nemirtingas/nemirtingas_steam_emu/-/blob/master/overlay/windows/DX11_Hook.cpp#L165-169

**Comment by acidicoala** [comment]
Does it work with Civ6? Because my simple `ResizeBuffers` hook works fine in Remnant and probably all other UE4 games. Civ6 seems to handle everything differently...

**Comment by Nemirtingas** [comment]
I didn't test on Epic. But my implementation did work on many steam games. There are a lot of games out there, and their implementations vary a lot.

**Comment by acidicoala** [comment]
The way ScreamAPI is handling resizing now is functionally equivalent to the methods in those 3 files, except for the
```cpp
pContext->Release();
pDevice->Release();
```
part, which actually crashes Civilization VI. Without this, the game is handling full-screen resizing without any issues. However, in windowed/borderless windowed mode the overlay simply does not render. At least the game doesn't crash now (for the most part).

**Comment by Nemirtingas** [comment]
It might crash because your overlay hook doesn't increase the reference count. If so, calling Release will free the DirectX device ;)

**Comment by acidicoala** [comment]
Oh ok. I don't think I am increasing it then since it does crash if I release the device inside the resize hook. I also noticed that in cases where my overlay fails, the Epic's legit overlay fails too, so I don't think there is anything left to be done here so I'll close this issue for now.
