### ISSUE TITLE
CreateTexture2D is crashing Railway Empire & Dungeons 3

### ISSUE THREAD

**Issue by acidicoala** [acidicoala/ScreamAPI#7]
For some reason overlay in the [Railway Empire](https://www.epicgames.com/store/en-US/product/railway-empire/home) fails to load the achievement icons. I have been able to narrow it down to this function call: https://github.com/acidicoala/ScreamAPI/blob/bf5680b1c177738f2e342d0169fe7a08568be8ef/Overlay/src/Loader.cpp#L107
The crashes are rather inconsistent, so sometimes it may stop at 5th texture, sometimes at 55th... And strangely enough, sometimes the game continues working, so you can interact with buttons and hear feedback, but the graphics are completely frozen.

Posting it here in the hope that someone who is profficient in DirectX11 can diagnose the issue.

**Comment by Nemirtingas** [comment]
This may happen when the D3D11Device is used somewhere else while the texture is being created. You should use a lock so the D3D Device is not in use while you create the texture and/or render the overlay.

**Comment by Nemirtingas** [comment]
Hi,
Maybe you can try to set the texture after allocating it ?
```
    ID3D11ShaderResourceView* resource = nullptr;

    // Create texture
    D3D11_TEXTURE2D_DESC desc = {};
    desc.Width = static_cast<UINT>(width);
    desc.Height = static_cast<UINT>(height);
    desc.MipLevels = 1;
    desc.ArraySize = 1;
    desc.Format = DXGI_FORMAT_R8G8B8A8_UNORM;
    desc.SampleDesc.Count = 1;
    desc.Usage = D3D11_USAGE_DEFAULT;
    desc.BindFlags = D3D11_BIND_SHADER_RESOURCE;
    desc.CPUAccessFlags = 0;

    ID3D11Texture2D* pTexture = nullptr;
    if (SUCCEEDED(pDevice->CreateTexture2D(&desc, nullptr, &pTexture)) && pTexture != nullptr)
    {
        D3D11_BOX box{};
        box.right = width;
        box.bottom = height;
        box.back = 1;
        pContext->UpdateSubresource(pTexture, 0, &box, image_buffer, desc.Width * 4, desc.Width * 4 * desc.Height);

        // Create texture view
        D3D11_SHADER_RESOURCE_VIEW_DESC srvDesc{};
        srvDesc.Format = DXGI_FORMAT_R8G8B8A8_UNORM;
        srvDesc.ViewDimension = D3D11_SRV_DIMENSION_TEXTURE2D;
        srvDesc.Texture2D.MipLevels = desc.MipLevels;
        srvDesc.Texture2D.MostDetailedMip = 0;

        pDevice->CreateShaderResourceView(pTexture, &srvDesc, &resource);
        // Release Texture, the shader resource increases the reference count.
        pTexture->Release();
    }

    return resource;
```

**Comment by acidicoala** [comment]
Hi @Nemirtingas,
Thanks for the suggestion, I will check it out later next week since I would need to re-download the game files again.

P.S. I am curious what you think of [this](https://cs.rin.ru/forum/viewtopic.php?f=20&t=109070)

**Comment by Nemirtingas** [comment]
Total War games often use Steam CEG protection and/or Denuvo. What are you actually trying to do ?

**Comment by acidicoala** [comment]
I'm just curious about their usage of the clockworks API/SDK, of which I could not find any references online. We could probably see other games adapting it as a cross-DRM solution, given the proliferation of non-Steam platforms.

**Comment by Nemirtingas** [comment]
I guess its their own API like the UPlay API. They won't provide the documentation if its an internal project. As long as they don't start their own cloud platform I guess we're pretty safe. Fat chance its just a big wrapper so they don't have to switch between steam/epic api when building their games.

**Comment by acidicoala** [comment]
It probably is indeed a cross platform wrapper. I was just wondering if there have been other games using it. Because at a glance it really looks like a generic wrapper which is not tied to a particular game developer. So I thought perhaps in the future we might see it other games so it's good be aware of it early on. I guess we'll just have to wait and see.

**Comment by Nemirtingas** [comment]
I have absolutely no idea. I'm not really a player, so I don't really look for this kind of infos.

**Comment by Nemirtingas** [comment]
Strange, since this week, when sometimes when calling ID3D11Device::CreateTexture2D, it hangs in a dll of the NVidia Driver (nvwgf2um.dll).

**Comment by acidicoala** [comment]
I actually still have 452.06 and didn't upgrade it yet. Thanks for the heads-up, I will stay away from the updates for a while.

**Comment by Nemirtingas** [comment]
Hi, maybe you should try to remove the async load of icons. I have some issues that when creating resources from another thread than the D3D device thread makes some games hangs on the creation of the textures.

**Comment by acidicoala** [comment]
> Hi, maybe you should try to remove the async load of icons. I have some issues that when creating resources from another thread than the D3D device thread makes some games hangs on the creation of the textures.

Well unfortunately that will have very noticeable startup time impact. The whole UI will freeze for several minutes if I do it on the thread where I get the D3D11 device. Doing all texture loading in only 1 new thread will help, but still it takes about half a second for a texture to load, so in games with several hundred achievements (like Civ 6) it would take several minutes to load them all.

**Comment by Nemirtingas** [comment]
Not if you download/read cache asyncly and load 1 image/frame.

**Comment by acidicoala** [comment]
> Not if you download/read cache asyncly and load 1 image/frame in your rendering function.

Hmm, that might actually work. I'll try it once I have finished downloading the game files. Thanks again for the tip.

**Comment by Nemirtingas** [comment]
> 
> 
> > Not if you download/read cache asyncly and load 1 image/frame in your rendering function.
> 
> Hmm, that might actually work. I'll try it once I have finished downloading the game files. Thanks again for the tip.

Thats my workaround actually. It used to work fine, but I don't know why, now lots of my games crash or hangs... Even if [ID3D11Device::CheckFeatureSupport](https://docs.microsoft.com/en-us/windows/win32/api/d3d11/nf-d3d11-id3d11device-checkfeaturesupport)(D3D11_FEATURE_THREADING) reports that it supports multi-threading ...

**Comment by acidicoala** [comment]
Wow, so the `pContext->UpdateSubresource(...)` method really did fix the crashing issues with Railway Empire. Thanks a lot, mate, I have added you to the Acknowledgements list of the 1st post in the forum topic since you have fixed several of my bugs by now.

**Comment by Nemirtingas** [comment]
Sincerely, I didn't believe that just calling UpdateSubresource would fix the issue.

**Comment by acidicoala** [comment]
Well, apparently it did :)

**Comment by acidicoala** [comment]
This issue is still present in Dungeons 3 and Railway Empire, both of which are published by Kalypso.

**Comment by Nemirtingas** [comment]
Did you try to load the textures when you're on the rendering thread ?
Also you should try pre-compiled shaders as some games block the hotbuild.

**Comment by acidicoala** [comment]
> Did you try to load the textures when you're on the rendering thread ?
> Also you should try pre-compiled shaders as some games block the hotbuild.

I haven't tried loading on the rendering thread. I kinda gave up on this issue a while ago, but I may try this method in the future.
And I have no idea about pre-compiled shaders :/

**Comment by Nemirtingas** [comment]
I've pre-compiled all ImGui shaders for my emus:
https://gitlab.com/Nemirtingas/nemirtingas_steam_emu/-/blob/master/extra/ImGui/impls/windows/imgui_shaderblobs.h
https://gitlab.com/Nemirtingas/nemirtingas_steam_emu/-/blob/master/extra/ImGui/impls/windows/imgui_shaderblobs.cpp

You then need to load the blobs directly instead of calling the D3D shader compiler:
https://gitlab.com/Nemirtingas/nemirtingas_steam_emu/-/blob/master/extra/ImGui/impls/windows/imgui_impl_dx11.cpp#L351

**Comment by acidicoala** [comment]
I think the repo is private, because it shows 404 for me
